version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: autonomous_agent.Dockerfile
    container_name: autonomous_agent
    environment:
      - QDRANT_HOST=qdrant
      - MODEL_HOST=model
    depends_on:
      - qdrant
      - model
  qdrant:
    image: qdrant/qdrant:v1.1.0
    ports:
    - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
  model:
    build:
      context: .
      dockerfile: model.Dockerfile
    container_name: model
    ports:
      - 5000:5000
    hostname: model